FROM ubuntu:16.04

RUN apt-get update -y
RUN apt-get upgrade -y

RUN apt-get install -y curl nginx python3 python3-pip

ADD ./requirements.txt /root/
WORKDIR /root/
RUN pip3 install -r requirements.txt

ADD ./ictsc_prep_school /root/

#CMD ["uwsgi","--http",":80","--module","ictsc_prep_school.wsgi"]
CMD ["python3","manage.py","runserver","0.0.0.0:80"]
