apiVersion: v1
kind: Pod
metadata:
  name: pstate
  labels:
    app: pstate
spec:
  containers:
  - name: pstate
    image: pstate_webui:20180410
    ports:
    - name: pstate
      containerPort: 80
      protocol: TCP
