---
# Source: base-system/templates/kong-configMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.conf: |-
    proxy_listen = 0.0.0.0:80, 0.0.0.0:443 ssl
    admin_listen = 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ssl_cert = /var/ssl/cert.pem                     # The absolute path to the SSL certificate for
    ssl_cert_key = /var/ssl/privkey.pem                # The absolute path to the SSL key for
    

---
# Source: base-system/templates/kong-pv.yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kong-pv-volume
  labels:
    volume: kong-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/volume/kong/ssl"

---
# Source: base-system/templates/postgresql-pv.yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresql-pv-volume
  labels:
    volume: postgresql-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/volume/postgresql"


---
# Source: base-system/templates/kong-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kong-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: kong-pv

---
# Source: base-system/templates/postgresql-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: postgresql-pv

---
# Source: base-system/templates/kong-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy-ssl
#  namespace: base-system
spec:
  type: NodePort
  ports:
  - name: kong-proxy-ssl
    port: 443
    targetPort: 443
    nodePort: 443
    protocol: TCP
  selector:
    app: kong

---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin-ssl
#  namespace: base-system
spec:
  type: ClusterIP
  ports:
  - name: kong-admin-ssl
    port: 8444
    targetPort: 8444
    protocol: TCP
  selector:
    app: kong

---
# Source: base-system/templates/postgresql-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
  - name: pgql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgresql

---
# Source: base-system/templates/kong-deployment.yaml
apiVersion: v1
kind: Pod
metadata:
  name: kong-pod
  labels:
    app: kong
spec:
  volumes:
    - name: kong-pv-storage
      persistentVolumeClaim:
        claimName: kong-pv-claim
    - name: kong-config
      configMap:
        name: kong-config
  containers:
  - name: kong
    image: kong:0.13.1
    env:
      - name: KONG_ADMIN_LISTEN
        value: "0.0.0.0:443 ssl"
      - name: KONG_ADMIN_LISTEN
        value: "0.0.0.0:8444 ssl"
      - name: KONG_PG_PASSWORD
        value: kong
      - name: KONG_PG_HOST
        value: postgresql
      - name: KONG_PROXY_ACCESS_LOG
        value: "/dev/stdout"
      - name: KONG_ADMIN_ACCESS_LOG
        value: "/dev/stdout"
      - name: KONG_PROXY_ERROR_LOG
        value: "/dev/stderr"
      - name: KONG_ADMIN_ERROR_LOG
        value: "/dev/stderr"
    ports:
    - name: proxy-ssl
      containerPort: 443
      protocol: TCP
    - name: admin-ssl
      containerPort: 8444
      protocol: TCP
    volumeMounts:
      - mountPath: "/etc/kong"
        name: kong-config
      - mountPath: "/var/ssl"
        name: kong-pv-storage
  initContainers:
  - name: init-kong
    image: kong:0.13.1
    env:
      - name: KONG_NGINX_DAEMON
        value: 'off'
      - name: KONG_PG_PASSWORD
        value: kong
      - name: KONG_PG_HOST
        value: postgresql
    command: [ "/bin/sh", "-c", "sleep 15 && kong migrations up" ]
    volumeMounts:
      - mountPath: "/etc/kong"
        name: kong-config
      - mountPath: "/var/ssl"
        name: kong-pv-storage

---
# Source: base-system/templates/postgresql-deployment.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: postgresql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:9.6
          env:
            - name: POSTGRES_USER
              value: kong
            - name: POSTGRES_PASSWORD
              value: kong
            - name: POSTGRES_DB
              value: kong
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-pv-storage
      volumes:
        - name: postgresql-pv-storage
          persistentVolumeClaim:
            claimName: postgresql-pv-claim      

