apiVersion: v1
kind: Pod
metadata:
  name: pstate-worker
  labels:
    app: pstate-worker
spec:
  containers:
  - name: pstate-worker
    image: terraform-manager-worker:20180816011
    env:
    - name: DJANGO_SETTINGS_MODULE
      value: ictsc_prep_school.settings.terraform_manager.develop
    - name: POSTGRES_DB
      value: pstate
    - name: POSTGRES_USER
      value: pstate
    - name: POSTGRES_PASSWORD # This is the password for the development environment.
      value: t0FPoJaZ
    - name: SCORE_SERVER_API_URL
      value: http://localhost:8900
    - name: SCORE_SERVER_AUTH_USER_NAME
      value: staff
    - name: SCORE_SERVER_AUTH_PASSWORD
      value: staff
