apiVersion: v1
kind: Pod
metadata:
  name: pstate-worker
  labels:
    app: pstate-worker
spec:
  containers:
  - name: pstate-worker
    image: terraform-manager-worker:20180705
    env:
    - name: DJANGO_SETTINGS_MODULE
      value: ictsc_prep_school.settings.terraform_manager.develop