---
# Source: pstate/templates/pstate-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pstate-service
spec:
  type: ClusterIP
  ports:
  - name: pstate
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: pstate

---
# Source: pstate/templates/pstate-deployment.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pstate
  labels:
    app: pstate
spec:
  containers:
  - name: pstate
    image: pstate_webui:20180823012
    ports:
    - name: pstate
      containerPort: 80
      protocol: TCP
    env:
    - name: DJANGO_SETTINGS_MODULE
      value: ictsc_prep_school.settings.pstate.develop

