apiVersion: v1
kind: Pod
metadata:
  name: pstate-notify-worker
  labels:
    app: pstate-notify-worker
spec:
  containers:
  - name: pstate-notify-worker
    image: pstate_webui:20181214016
    env:
    - name: DJANGO_SETTINGS_MODULE
      value: ictsc_prep_school.settings.pstate.develop
    - name: POSTGRES_DB
      value: pstate
    - name: POSTGRES_USER
      value: pstate
    - name: POSTGRES_PASSWORD # This is the password for the development environment.
      value: t0FPoJaZ
    - name: MODE
      value: notify
    - name: SCORE_SERVER_API_URL
      value: http://localhost:8900
    - name: SCORE_SERVER_AUTH_USER_NAME
      value: staff
    - name: SCORE_SERVER_AUTH_PASSWORD
      value: staff
