# Generated by Django 2.0.4 on 2018-04-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='問題名(管理用)')),
                ('display_name', models.CharField(max_length=200, verbose_name='問題名(参加者向け)')),
                ('description', models.TextField(verbose_name='問題文')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='問題公開日時')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='問題公開終了日時')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='公開フラグ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProblemEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vnc_server_ipv4_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('vnc_server_port', models.CharField(blank=True, max_length=5, null=True)),
                ('vnc_server_username', models.CharField(blank=True, max_length=50, null=True)),
                ('vnc_server_password', models.CharField(blank=True, max_length=50, null=True)),
                ('is_enabled', models.BooleanField(default=False, verbose_name='有効フラグ')),
                ('state', models.CharField(choices=[('IN_PREPARATION', 'IN_PREPARATION'), ('READY', 'READY'), ('IN_PROGRESS', 'IN_PROGRESS'), ('FINISH', 'FINISH'), ('WAITING_FOR_SCORING', 'WAITING_FOR_SCORING'), ('WAITING_FOR_DELETE', 'WAITING_FOR_DELETE'), ('DELETED', 'DELETED')], default='IN_PREPARATION', max_length=100)),
                ('participant', models.ForeignKey(on_delete=False, to='pstate.Participant')),
                ('problem', models.ForeignKey(on_delete=False, to='pstate.Problem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('team_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('remarks', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='problemenvironment',
            name='team',
            field=models.ForeignKey(on_delete=False, to='pstate.Team'),
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='pstate.Team'),
        ),
        migrations.AddField(
            model_name='grade',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='pstate.Participant'),
        ),
        migrations.AddField(
            model_name='grade',
            name='problem',
            field=models.ForeignKey(on_delete=False, to='pstate.Problem'),
        ),
        migrations.AddField(
            model_name='grade',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='pstate.Team'),
        ),
    ]
