# Generated by Django 2.0.4 on 2018-05-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraform_manager', '0001_initial'),
        ('pstate', '0002_auto_20180507_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='terraform_file_id',
            field=models.ForeignKey(null=True, on_delete=False, to='terraform_manager.TerraformFile'),
        ),
        migrations.AddField(
            model_name='problemenvironment',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=True, to='terraform_manager.Environment'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='問題文'),
        ),
    ]
