# Generated by Django 2.0.4 on 2018-05-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pstate', '0004_auto_20180507_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_team',
            field=models.BooleanField(default=False),
        ),
    ]
