# Generated by Django 2.0.4 on 2018-05-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pstate', '0005_user_is_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemEnvironmentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('before_state', models.CharField(blank=True, choices=[('IN_PREPARATION', 'IN_PREPARATION'), ('READY', 'READY'), ('IN_PROGRESS', 'IN_PROGRESS'), ('FINISH', 'FINISH'), ('WAITING_FOR_SCORING', 'WAITING_FOR_SCORING'), ('WAITING_FOR_DELETE', 'WAITING_FOR_DELETE'), ('DELETED', 'DELETED')], max_length=100, null=True)),
                ('after_state', models.CharField(blank=True, choices=[('IN_PREPARATION', 'IN_PREPARATION'), ('READY', 'READY'), ('IN_PROGRESS', 'IN_PROGRESS'), ('FINISH', 'FINISH'), ('WAITING_FOR_SCORING', 'WAITING_FOR_SCORING'), ('WAITING_FOR_DELETE', 'WAITING_FOR_DELETE'), ('DELETED', 'DELETED')], max_length=100, null=True)),
                ('problem_environment', models.ForeignKey(on_delete=True, related_name='logs', to='pstate.ProblemEnvironment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
