# Generated by Django 2.0.4 on 2018-05-14 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pstate', '0006_problemenvironmentlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemenvironment',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='terraform_manager.Environment'),
        ),
        migrations.AlterField(
            model_name='problemenvironmentlog',
            name='problem_environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pstate.ProblemEnvironment'),
        ),
    ]
