# Generated by Django 2.0.4 on 2018-05-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pstate', '0007_auto_20180514_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemenvironment',
            name='state',
            field=models.CharField(choices=[('IN_PREPARATION', 'IN_PREPARATION'), ('READY', 'READY'), ('IN_PROGRESS', 'IN_PROGRESS'), ('FINISH', 'FINISH'), ('WAITING_FOR_SCORING', 'WAITING_FOR_SCORING'), ('SCORING_HAS_ENDED', 'SCORING_HAS_ENDED'), ('WAITING_FOR_DELETE', 'WAITING_FOR_DELETE'), ('DELETED', 'DELETED')], default='IN_PREPARATION', max_length=100),
        ),
        migrations.AlterField(
            model_name='problemenvironmentlog',
            name='after_state',
            field=models.CharField(blank=True, choices=[('IN_PREPARATION', 'IN_PREPARATION'), ('READY', 'READY'), ('IN_PROGRESS', 'IN_PROGRESS'), ('FINISH', 'FINISH'), ('WAITING_FOR_SCORING', 'WAITING_FOR_SCORING'), ('SCORING_HAS_ENDED', 'SCORING_HAS_ENDED'), ('WAITING_FOR_DELETE', 'WAITING_FOR_DELETE'), ('DELETED', 'DELETED')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='problemenvironmentlog',
            name='before_state',
            field=models.CharField(blank=True, choices=[('IN_PREPARATION', 'IN_PREPARATION'), ('READY', 'READY'), ('IN_PROGRESS', 'IN_PROGRESS'), ('FINISH', 'FINISH'), ('WAITING_FOR_SCORING', 'WAITING_FOR_SCORING'), ('SCORING_HAS_ENDED', 'SCORING_HAS_ENDED'), ('WAITING_FOR_DELETE', 'WAITING_FOR_DELETE'), ('DELETED', 'DELETED')], max_length=100, null=True),
        ),
    ]
