# Generated by Django 2.0.4 on 2018-06-19 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pstate', '0008_auto_20180514_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pstate.Participant'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pstate.Problem'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pstate.Team'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='assign_team',
            field=models.ForeignKey(blank=True, help_text='所属するチームを選択してください', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant', to='pstate.Team', verbose_name='所属チーム'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='terraform_file_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terraform_manager.TerraformFile'),
        ),
        migrations.AlterField(
            model_name='problemenvironment',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pstate.Participant'),
        ),
        migrations.AlterField(
            model_name='problemenvironment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pstate.Problem'),
        ),
        migrations.AlterField(
            model_name='problemenvironment',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pstate.Team'),
        ),
    ]
