# Generated by Django 2.0.4 on 2018-07-22 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pstate', '0010_auto_20180619_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemenvironment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_environment', to='pstate.Problem'),
        ),
    ]
