# Generated by Django 2.0.4 on 2019-07-16 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pstate', '0013_auto_20190716_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 16, 2, 44, 40, 837721, tzinfo=utc), null=True, verbose_name='問題公開終了日時'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 16, 2, 44, 40, 837694, tzinfo=utc), null=True, verbose_name='問題公開日時'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
