# Generated by Django 2.0.4 on 2019-08-01 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pstate', '0015_auto_20190801_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='問題公開終了日時'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='問題公開日時'),
        ),
    ]
