# Generated by Django 2.0.4 on 2019-07-30 15:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pstate', '0016_auto_20190801_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('git_source', models.CharField(help_text='git://github.com:sample/sample.git', max_length=200, verbose_name='git source')),
                ('ssh_private_key', models.TextField(blank=True, verbose_name='SSH private key')),
                ('project_root_path', models.CharField(blank=True, default='/ictsc2019', help_text='/ictscXXXX', max_length=200)),
                ('teams_file', models.CharField(default='teams.yml', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='problem',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 30, 15, 39, 22, 632592, tzinfo=utc), null=True, verbose_name='問題公開終了日時'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 30, 15, 39, 22, 632541, tzinfo=utc), null=True, verbose_name='問題公開日時'),
        ),
    ]
