# Generated by Django 2.0.4 on 2019-08-01 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terraform_manager', '0008_environment_tfstate'),
        ('pstate', '0016_auto_20190801_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.TextField()),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_queue', to='terraform_manager.Environment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
