# Generated by Django 2.0.4 on 2019-08-01 05:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pstate', '0016_auto_20190801_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='github',
            name='name',
            field=models.CharField(default='ictsc-problems', max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 1, 5, 5, 44, 184187, tzinfo=utc), null=True, verbose_name='問題公開終了日時'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 1, 5, 5, 44, 184147, tzinfo=utc), null=True, verbose_name='問題公開日時'),
        ),
    ]
