# Generated by Django 2.0.4 on 2019-08-01 04:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pstate', '0015_auto_20190731_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='github',
            name='problem_path',
            field=models.CharField(blank=True, default='q1', help_text='問題コードのディレクトリが保存されている場所。予選1ならq1', max_length=200),
        ),
        migrations.AlterField(
            model_name='github',
            name='project_root_path',
            field=models.CharField(blank=True, default='ictsc2019', help_text='ictscXXXX', max_length=200),
        ),
        migrations.AlterField(
            model_name='problem',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 1, 4, 14, 48, 816262, tzinfo=utc), null=True, verbose_name='問題公開終了日時'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 1, 4, 14, 48, 816224, tzinfo=utc), null=True, verbose_name='問題公開日時'),
        ),
    ]
