# Generated by Django 2.0.4 on 2019-08-05 11:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('terraform_manager', '0009_filetemplate'),
        ('pstate', '0019_auto_20190801_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.TextField()),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_queue', to='terraform_manager.Environment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='problem',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='問題公開終了日時'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='問題公開日時'),
        ),
    ]
