kind: PersistentVolume
apiVersion: v1
metadata:
  name: kong-pv-volume
  labels:
    volume: kong-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/volume/kong"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kong-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: kong-pv
