apiVersion: v1
kind: Service
metadata:
  name: relate-service
spec:
  type: ClusterIP
  ports:
  - name: relate
    port: 80
    targetPort: 7777
    protocol: TCP
  selector:
    app: relate

---
apiVersion: v1
kind: Pod
metadata:
  name: relate
  labels:
    app: relate
spec:
  containers:
  - name: relate
    image: relate-webui:20180524
    ports:
    - name: relate
      containerPort: 7777
      protocol: TCP
