kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kong-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: kong-pv
