kind: PersistentVolume
apiVersion: v1
metadata:
  name: kong-pv-volume
  labels:
    volume: kong-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/volume/kong/ssl"
