apiVersion: v1
kind: Pod
metadata:
  name: kong-pod
  namespace: base-system
  labels:
    app: kong
spec:
  volumes:
    - name: kong-pv-storage
      persistentVolumeClaim:
        claimName: kong-pv-claim
  containers:
  - name: kong
    image: kong:0.13.1
    env:
      - name: KONG_ADMIN_LISTEN
        value: "0.0.0.0:443 ssl"
      - name: KONG_ADMIN_LISTEN
        value: "0.0.0.0:8444 ssl"
      - name: KONG_PG_PASSWORD
        value: kong
      - name: KONG_PG_HOST
        value: postgres
      - name: KONG_PROXY_ACCESS_LOG
        value: "/dev/stdout"
      - name: KONG_ADMIN_ACCESS_LOG
        value: "/dev/stdout"
      - name: KONG_PROXY_ERROR_LOG
        value: "/dev/stderr"
      - name: KONG_ADMIN_ERROR_LOG
        value: "/dev/stderr"
    ports:
    - name: proxy-ssl
      containerPort: 443
      protocol: TCP
      hostPort: 443
    - name: admin-ssl
      containerPort: 8444
      protocol: TCP
    volumeMounts:
      - mountPath: "/etc/kong"
        name: kong-pv-storage
  initContainers:
  - name: init-kong
    image: kong:0.13.1
    env:
      - name: KONG_NGINX_DAEMON
        value: 'off'
      - name: KONG_PG_PASSWORD
        value: kong
      - name: KONG_PG_HOST
        value: postgres.base-system.svc.cluster.local
    command: [ "/bin/sh", "-c", "kong migrations up" ]
    volumeMounts:
      - mountPath: "/etc/kong"
        name: kong-pv-storage
