# Generated by Django 2.0.4 on 2018-05-02 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('IN_WAITING_FOR_START', 'IN_WAITING_FOR_START'), ('IN_FILE_COPYING', 'IN_FILE_COPYING'), ('IN_INITIALIZE', 'IN_INITIALIZE'), ('INITIALIZED', 'INITIALIZED'), ('IN_PLANNING', 'IN_PLANNING'), ('PLANNED', 'PLANNED'), ('IN_APPLYING', 'IN_APPLYING'), ('APPLIED', 'APPLIED'), ('IN_DESTROYING', 'IN_DESTROYING'), ('DESTROYED', 'DESTROYED'), ('FAILED', 'FAILED')], default='IN_WAITING_FOR_START', max_length=20)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_code', models.IntegerField(blank=True)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=True, to='terraform_manager.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_name', models.CharField(max_length=100)),
                ('attribute', models.ManyToManyField(blank=True, to='terraform_manager.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='ShellScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TerraformFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('file_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=False, to='terraform_manager.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='terraformfile',
            name='variables',
            field=models.ManyToManyField(blank=True, to='terraform_manager.Variable'),
        ),
        migrations.AddField(
            model_name='shellscript',
            name='terraform_file',
            field=models.ForeignKey(on_delete=True, related_name='shell_script', to='terraform_manager.TerraformFile'),
        ),
        migrations.AddField(
            model_name='environment',
            name='terraform_file',
            field=models.ForeignKey(on_delete=True, to='terraform_manager.TerraformFile'),
        ),
    ]
