# Generated by Django 2.0.4 on 2018-05-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraform_manager', '0002_auto_20180507_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='environment',
            field=models.ForeignKey(on_delete=True, related_name='logs', to='terraform_manager.Environment'),
        ),
    ]
