# Generated by Django 2.0.4 on 2018-05-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terraform_manager', '0003_auto_20180507_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environment',
            old_name='locked',
            new_name='is_locked',
        ),
    ]
