# Generated by Django 2.0.4 on 2018-05-14 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terraform_manager', '0004_auto_20180514_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='terraform_file',
            field=models.ForeignKey(on_delete=False, to='terraform_manager.TerraformFile'),
        ),
        migrations.AlterField(
            model_name='log',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='terraform_manager.Environment'),
        ),
        migrations.AlterField(
            model_name='shellscript',
            name='terraform_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shell_script', to='terraform_manager.TerraformFile'),
        ),
    ]
