# Generated by Django 2.0.4 on 2018-06-19 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terraform_manager', '0005_auto_20180514_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='terraform_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terraform_manager.TerraformFile'),
        ),
        migrations.AlterField(
            model_name='terraformfile',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terraform_manager.Provider'),
        ),
    ]
