# Generated by Django 2.0.4 on 2018-07-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraform_manager', '0007_auto_20180619_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='tfstate',
            field=models.TextField(blank=True),
        ),
    ]
